#!/usr/bin/env bash
# pi-hooks/hooks/wire.sh -- called by `aphotic plugin install|enable
# pi-hooks` with one argument: core's lib/aphotic directory.
# Symlinks this plugin's own pi_omp_hook.js into the extension discovery
# directory of every installed pi-family harness (Pi and/or Oh My Pi;
# one adapter file serves both -- same extension API) and records
# core's agent_hook.py path in the shell's state dir, since the hook
# cannot derive that from its own location (see pi_omp_hook.js's own
# comment). The plugin repo stays the only place its logic lives: Pi
# follows a symlink, and OMP -- whose discovery scan ignores symlinks --
# gets a two-line re-export shim that loads the same file.
set -euo pipefail

# Keep in sync with the runtime's verified floor in the adapter.
MIN_PI_VERSION="1.0.0"
MIN_OMP_VERSION="18.5.1"

lib_dir="$1"
plugin_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
plugin_script="${plugin_dir}/hook/pi_omp_hook.js"
state_dir="${XDG_STATE_HOME:-$HOME/.local/state}/aphotic"
hook_config="$state_dir/pi-hook.json"
link_name="aphotic_pi_hook.js"

command -v jq >/dev/null 2>&1 || { echo "jq not found; cannot wire Pi hooks" >&2; exit 1; }
[[ -f "$plugin_script" ]] || { echo "pi_omp_hook.js not found at $plugin_script" >&2; exit 1; }

# $1 = discovery dir, $2 = executable, $3 = version floor, $4 = how the
# adapter is installed: link (Pi follows symlinks) or shim (OMP's
# discovery scan ignores symlinks, so a real file that re-exports the
# adapter). Returns 1 when the harness is absent or too old; a
# per-target failure never aborts the other target or the config write.
wire_target() {
    local dest_dir="$1" exe="$2" floor="$3" kind="$4"
    if ! command -v "$exe" >/dev/null 2>&1; then
        echo "note: $exe not found; skipping its discovery dir." >&2
        return 1
    fi
    harness_present=1
    local found
    found="$("$exe" --version 2>/dev/null | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1 || true)"
    if [[ -n "$found" && "$(printf '%s\n%s\n' "$found" "$floor" | sort -V | head -n1)" != "$floor" ]]; then
        # A harness that has been downgraded under the floor would load
        # a hook it cannot run: take the link down, not leave it lying.
        rm -f "$dest_dir/$link_name"
        echo "$exe $found is too old for this hook (needs >= $floor); unwired." >&2
        return 1
    elif [[ -z "$found" ]]; then
        echo "WARNING: could not parse a $exe version; wiring anyway." >&2
    fi
    mkdir -p "$dest_dir"
    case "$kind" in
        link)
            ln -sfn "$plugin_script" "$dest_dir/$link_name"
            ;;
        shim)
            # A hand-placed file of this name is retired by the overwrite:
            # two copies of the adapter would count every session twice.
            printf '%s\n' \
                "// Aphotic pi-hooks wiring: OMP's discovery scan ignores symlinks, so" \
                "// this is a real file that loads the plugin's single adapter source." \
                "// Regenerated by wire.sh -- edits belong in the pi-hooks plugin." \
                "export { default } from \"$plugin_script\";" \
                > "$dest_dir/$link_name"
            ;;
    esac
    return 0
}

harness_present=0
wire_target "$HOME/.pi/agent/extensions" "pi" "$MIN_PI_VERSION" link || true
wire_target "$HOME/.omp/agent/hooks/pre" "omp" "$MIN_OMP_VERSION" shim || true
if [[ "$harness_present" -eq 0 ]]; then
    echo "Neither pi nor omp is installed; nothing to wire." >&2
    exit 1
fi

mkdir -p "$state_dir"
jq -n --arg p "${lib_dir}/agent_hook.py" '{agentHookPy: $p}' > "$hook_config"

# Extensions load at process start; a running session keeps the module it
# already loaded. A restart is the reliable path.
for exe in pi omp; do
    if command -v "$exe" >/dev/null 2>&1 && pgrep -x "$exe" >/dev/null 2>&1; then
        echo "note: $exe is running; restart it to pick up the hook." >&2
    fi
done
