#!/usr/bin/env bash
# One-time setup for the OpenRGB Sync plugin. Safe to re-run any time your
# RGB hardware changes (new fans, a replaced waterblock, a new hub channel
# wired up, etc).
#
# There is no post-install hook in the plugin contract yet (see
# PLUGIN_SYSTEM.md -- install runs dependency install, UI-module linking
# and harness wiring, nothing plugin-defined), so this is a script you run
# once by hand after `aphotic plugin install openrgb`. The hooks nudge you
# here with a desktop notification when they detect one of the conditions
# below rather than failing quietly.
#
# What it checks, and why none of it can happen inside a theme-change hook:
#   1. python3 + the openrgb-python SDK module.
#   2. The udev rules file. Without it the kernel denies hidraw/i2c access
#      to your RGB controllers, and OpenRGB's SDK server then answers a
#      connection perfectly happily while reporting zero devices -- which
#      is why this presents as "connected, nothing lights up" rather than
#      as an obvious permission error. Installing the rules needs root, so
#      it is offered here with an explicit y/N and never done silently.
#   3. The I2C/SMBus kernel module needed for DRAM RGB and some
#      motherboard lighting -- same deal, prints the command, never runs
#      modprobe for you.
#   4. Zones reporting 0 LEDs (controller/hub channels OpenRGB genuinely
#      cannot autodetect), and walks you through sizing them into
#      zones.conf, which every apply reasserts.
set -euo pipefail

# shellcheck source=../lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

RULES_DEST="/etc/udev/rules.d/60-openrgb.rules"
RULES_SEARCH=(
  /usr/lib/udev/rules.d/60-openrgb.rules
  /lib/udev/rules.d/60-openrgb.rules
  /etc/udev/rules.d/60-openrgb.rules
)
RULES_SOURCE_SEARCH=(
  /usr/share/OpenRGB/60-openrgb.rules
  /usr/share/openrgb/60-openrgb.rules
  /opt/OpenRGB/60-openrgb.rules
  "$HOME/OpenRGB/60-openrgb.rules"
)

echo "== OpenRGB Sync setup =="
echo

openrgb_plugin_bootstrap_config
openrgb_plugin_load_settings

# ---------------------------------------------------------------- python
echo "-- Python SDK client --"
if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 not found on PATH -- install it first." >&2
  exit 1
fi
if python3 -c 'import openrgb' 2>/dev/null; then
  echo "OK: the 'openrgb' Python module is importable."
else
  cat <<'EOF'
MISSING: the openrgb-python SDK client isn't installed, so nothing can be
applied. Install it whichever way you prefer:

    # distro package (search your repos/AUR for openrgb-python)
    # or, user-local:
    python3 -m pip install --user openrgb-python

This is not installed for you -- it's a Python package on your system, not
something a theming plugin should be putting there behind your back.
EOF
fi
echo

# ------------------------------------------------------------------ udev
echo "-- Device access (udev rules) --"
existing_rules=""
for candidate in "${RULES_SEARCH[@]}"; do
  [[ -f "$candidate" ]] && existing_rules="$candidate" && break
done
if [[ -z "$existing_rules" ]]; then
  for dir in /usr/lib/udev/rules.d /lib/udev/rules.d /etc/udev/rules.d; do
    found="$(find "$dir" -maxdepth 1 -iname '*openrgb*.rules' 2>/dev/null | head -n1 || true)"
    [[ -n "$found" ]] && existing_rules="$found" && break
  done
fi

if [[ -n "$existing_rules" ]]; then
  echo "OK: udev rules present at $existing_rules"
else
  cat <<'EOF'
MISSING: no 60-openrgb.rules udev file is installed.

Without it the kernel denies your user access to the hidraw/i2c nodes your
RGB controllers live on. OpenRGB still starts, its SDK server still accepts
connections -- it just enumerates zero devices, or fails every write. That
is the single most likely cause of a plugin that "connects fine and does
nothing", so it's worth fixing before anything else.

Note this is a rules file, not a reason to run OpenRGB as root -- running it
elevated papers over the problem and hands a GUI app more privilege than it
needs.
EOF
  echo

  rules_src=""
  # OpenRGB itself is the only trustworthy source for this file: it's a long
  # vendor/device table that gets stale, so it's copied from whatever your
  # OpenRGB install shipped rather than reproduced here from memory.
  if command -v openrgb >/dev/null 2>&1 && openrgb --help 2>&1 | grep -q -- '--gen-udev-rules'; then
    tmp_rules="$(mktemp)"
    if openrgb --gen-udev-rules > "$tmp_rules" 2>/dev/null && [[ -s "$tmp_rules" ]]; then
      rules_src="$tmp_rules"
      echo "Found a source: generated by 'openrgb --gen-udev-rules'."
    fi
  fi
  if [[ -z "$rules_src" ]]; then
    for candidate in "${RULES_SOURCE_SEARCH[@]}" "${1:-}"; do
      [[ -n "$candidate" && -f "$candidate" ]] && rules_src="$candidate" && break
    done
    [[ -n "$rules_src" ]] && echo "Found a source: $rules_src"
  fi

  if [[ -z "$rules_src" ]]; then
    cat <<EOF
No 60-openrgb.rules could be found on this system to install. Grab it from
the OpenRGB source tree (it lives at the repo root:
https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/60-openrgb.rules)
and re-run this script with its path:

    $0 /path/to/60-openrgb.rules

Or install it yourself:

    sudo install -m 0644 /path/to/60-openrgb.rules $RULES_DEST
    sudo udevadm control --reload-rules
    sudo udevadm trigger

Then replug (or reboot) and restart OpenRGB.
EOF
  else
    cat <<EOF

This would run, with sudo:

    sudo install -m 0644 $rules_src $RULES_DEST
    sudo udevadm control --reload-rules
    sudo udevadm trigger

EOF
    read -r -p "Install the udev rules now? [y/N]: " reply < /dev/tty 2>/dev/null || reply="n"
    if [[ "${reply,,}" == "y" || "${reply,,}" == "yes" ]]; then
      if sudo install -m 0644 "$rules_src" "$RULES_DEST" \
        && sudo udevadm control --reload-rules \
        && sudo udevadm trigger; then
        echo "Installed. Replug USB-attached controllers (or reboot) and restart OpenRGB."
        rm -f "$OPENRGB_PLUGIN_STATE_DIR/notified-udev" "$OPENRGB_PLUGIN_STATE_DIR/notified-udev-writes" 2>/dev/null || true
      else
        echo "Rules install failed -- run the three commands above manually." >&2
      fi
    else
      echo "Skipped. Nothing was changed."
    fi
  fi
fi
echo

# ------------------------------------------------------------------- i2c
echo "-- I2C/SMBus check (needed for DRAM RGB + some motherboard lighting) --"
if compgen -G '/dev/i2c-*' >/dev/null 2>&1; then
  echo "OK: /dev/i2c-* device nodes present."
else
  vendor="$(grep -m1 vendor_id /proc/cpuinfo 2>/dev/null | grep -o 'Intel\|AMD' || true)"
  smbus_mod="i2c-i801"
  [[ "$vendor" == "AMD" ]] && smbus_mod="i2c-piix4"
  cat <<EOF
MISSING: no /dev/i2c-* device nodes exist yet. RAM RGB (and some
motherboard SMBus lighting) won't be detected by OpenRGB until the
i2c-dev module is loaded. This needs root and is NOT run automatically
by this script or the plugin -- run it yourself:

    sudo modprobe i2c-dev $smbus_mod

To make it survive reboots:

    echo -e "i2c-dev\n$smbus_mod" | sudo tee /etc/modules-load.d/openrgb.conf

Re-run this script after loading the module to pick up newly-detected
devices for zone setup below.
EOF
fi
echo

# --------------------------------------------------------------- devices
echo "-- Device scan (via the SDK server on ${OPENRGB_SDK_HOST}:${OPENRGB_SDK_PORT}) --"
if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found on PATH -- needed for the zone-sizing walkthrough below. Install it and re-run." >&2
  exit 1
fi

inventory="$(python3 "$RGB_SYNC" devices --json 2>/dev/null || true)"
if [[ -z "$inventory" ]] || ! jq -e '.devices' >/dev/null 2>&1 <<<"$inventory"; then
  cat <<EOF
Could not reach OpenRGB's SDK server. Start OpenRGB with its server enabled:

    openrgb --server           # or enable "Enable SDK Server" in the GUI's
                               # Settings tab, then restart it

Everything above this line is still valid -- re-run this script once the
server is up to finish zone sizing.
EOF
  exit 1
fi

device_count="$(jq '.devices | length' <<<"$inventory")"
if [[ "$device_count" == 0 ]]; then
  cat <<EOF
Connected, but OpenRGB reports ZERO devices. If the udev section above said
MISSING, that's your answer -- install the rules, replug, restart OpenRGB
and re-run. Otherwise check OpenRGB's own detection with:

    openrgb -vv

This plugin can only sync devices OpenRGB itself can already see.
EOF
  exit 1
fi

jq -r '.devices[] | "  [\(.index)] \(.name) -- \(.leds) LEDs, static -> \(.static_mode // "none"), breathing -> \(.breathing_mode // "none")"' <<<"$inventory"
echo

zero_zones="$(jq -r '.devices[] as $d | $d.zones[] | select(.leds == 0) | "\($d.name)\t\(.index)\t\(.name)"' <<<"$inventory")"
if [[ -z "$zero_zones" ]]; then
  echo "Every detected zone already reports LEDs. Nothing to size."
else
  cat <<'EOF'
The zones below report 0 LEDs. These are "controller" style channels (fan
/RGB hubs, lighting nodes) where OpenRGB cannot autodetect how many LEDs
you actually have wired -- you have to tell it once. This is a real
OpenRGB limitation, not something this plugin can work around.

For each zone: count the actual LEDs on that channel (check the device/fan
spec sheet, or use the OpenRGB GUI's zone resize plus a test color to
confirm visually), then enter the count. Leave blank to skip -- it just
won't be color-synced. Some zones are a fixed single-LED type and can't be
resized at all; those are a hardware limit, not a failure.
EOF
  echo
  saved=0
  while IFS=$'\t' read -r dev_name zone_idx zone_name; do
    [[ -n "$dev_name" ]] || continue
    # Prompt on the tty explicitly: this loop's own stdin is the zone list.
    read -r -p "  $dev_name / zone $zone_idx ($zone_name) LED count [blank=skip]: " count < /dev/tty 2>/dev/null || count=""
    if [[ "$count" =~ ^[0-9]+$ && "$count" -gt 0 ]]; then
      if [[ -f "$ZONES_FILE" ]]; then
        grep -v -i "^${dev_name}:${zone_idx}:" "$ZONES_FILE" > "$ZONES_FILE.tmp" 2>/dev/null || true
        mv "$ZONES_FILE.tmp" "$ZONES_FILE"
      fi
      echo "${dev_name}:${zone_idx}:${count}" >> "$ZONES_FILE"
      echo "  -> saved to zones.conf."
      saved=$((saved + 1))
    fi
  done <<<"$zero_zones"
  if [[ "$saved" -gt 0 ]]; then
    echo
    echo "Applying the new sizes and the current theme color..."
    python3 "$RGB_SYNC" apply || true
  fi
fi

echo
echo "-- Devices not detected at all --"
cat <<'EOF'
If hardware you expect isn't in the scan above (a USB-header waterblock or
distroplate controller, for example), OpenRGB either needs the udev/I2C
fixes above, or has no driver for that specific controller yet. Check
OpenRGB's own compatible-device list, or run `openrgb -vv` for verbose
detection logs while the device is plugged in.
EOF

echo
echo "Setup complete."
echo "  Config: $OPENRGB_PLUGIN_CONFIG_DIR"
echo "  Log:    $OPENRGB_PLUGIN_STATE_DIR/sync.log"
echo "  Check what's actually applied any time with: $PLUGIN_DIR/scripts/rgb_sync.py status"
